# Generated by Django 2.2 on 2019-06-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieActor',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='persons',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.DeleteModel(
            name='MovieDirector',
        ),
    ]
