# Generated by Django 2.2 on 2019-06-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190610_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(null=True, on_delete=models.SET(''), to='movies.Country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_language',
            field=models.ForeignKey(null=True, on_delete=models.SET(''), to='movies.Language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(null=True, to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(null=True),
        ),
    ]
