# Generated by Django 2.2 on 2019-06-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20190613_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
    ]
