# Generated by Django 2.2 on 2019-06-18 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20190618_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='user_token',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Profile'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(to='movies.Person'),
        ),
    ]
