# Generated by Django 2.2 on 2019-06-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20190618_0254'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movierate',
            unique_together=set(),
        ),
    ]
