# Generated by Django 2.2 on 2019-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20190619_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='classification',
            field=models.CharField(choices=[('A', 'Todo publico'), ('B', '+12'), ('B15', '+15'), ('C', '+18'), ('D', 'Películas para adultos')], max_length=50, null=True),
        ),
    ]
