# Generated by Django 2.2 on 2019-06-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20190620_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
